package lookups

// symbols to code values - to be generated by a tool
// first value is de-facto default (0)

// user role
const (
	UserRoleGuest = iota
	UserRoleMember
	UserRoleAdmin
)

// language
const (
	LanguageEN = iota
	LanguageDE
)

// Game
const (
	GameFH4 = iota
	GameFH5
)

// Privacy
const (
	PrivacyUserName = iota
	PrivacyXboxTag
)

// visibility
const (
	VisibilityAll = iota
	VisibilityMembers
	VisibilityNone
)

// comment status
const (
	CommentStatusPending = iota
	CommentStatusVisible
	CommentStatusFlagged
	CommentStatusBlocked
)

// course type
const (
	CourseTypeStandard = iota
	CourseTypeCustom
)

// course style
const (
	CourseStyleCircuit = iota
	CourseStyleSprint
)

// series
const (
	SeriesRoad = iota
	SeriesDirt
	SeriesCross
)

// car class
const (
	CarClassA = iota
	CarClassB
	CarClassC
	CarClassD
	CarClassS1
	CarClassS2
	CarClassX
	CarClassOpen
	CarClassMixed
)
