package lookups

// symbols to code values - to be generated by a tool
// first value is de-facto default (0)

// user role
const (
	UserRoleGuest = iota
	UserRoleMember
	UserRoleAdmin
)

// language
const (
	LanguageEN = iota
	LanguageDE
)

// Game
const (
	GameFH4 = iota
	GameFH5
)

// visibility
const (
	VisibilityAll = iota
	VisibilityMembers
	VisibilityNone
)

// course type
const (
	CourseTypeStandard = iota
	CourseTypeCustom
)

// series
const (
	SeriesRoad = iota
	SeriesDirt
	SeriesCross
)

// car class
const (
	CarClassA = iota
	CarClassB
	CarClassC
	CarClassD
	CarClassS1
	CarClassS2
	CarClassX
	CarClassOpen
	CarClassMixed
)
