package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// File Name Convention at Destination:
// otype_uuid.ext

// UploadInfo contains the meta data of an uploaded file
type UploadInfo = struct {
	ID           string             // generated by controller
	UploadedTS   time.Time          `json:"UploadedTS" bson:"-"`
	UploadedID   primitive.ObjectID `json:"UploadedID" bson:"UploadedID"`
	UploadedName string             `json:"UploadedName" bson:"UploadedName"`
	SysFileName  string             `json:"-" bson:"fileName"`            // internal server file name
	OrigFileName string             `json:"fileName" bson:"origFileName"` // shown to client (uploader)
	Description  string             `json:"description" bson:"description,omitempty"`
	URL          string             `json:"url" bson:"-"`
	StatusCode   int32              `json:"statusCode" bson:"statusCD"` // TODO: Create Upload Status Code (?) or use comment's
	StatusText   string             `json:"statusText" bson:"-"`
	StatusTS     time.Time          `json:"statusTS" bson:"statusTS"`
	StatusID     primitive.ObjectID `json:"statusID" bson:"statusID"`
	StatusName   string             `json:"statusName" bson:"statusName"`
}
